backend:
  name: github
  repo: alexstapfofficial/landing-template
  branch: page

media_folder: "public/images/uploads"      # wohin Bilder gespeichert werden
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
